apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  clusterIP: None  # Headless Service 설정
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
