apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: SECRET_ROOT_PASSWORD
        - name: POSTGRES_DATABASE
          value: SPEAK_TO_YOU_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: SECRET_USERNAME
              name: postgresql-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SECRET_PASSWORD
              name: postgresql-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi

