apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # PV와 동일하게 8Gi 설정
  volumeName: postgresql-pv
  storageClassName: manual  # PV와 동일한 StorageClass 추가

