apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080      # 서비스 내부 포트
      targetPort: 8080 # 컨테이너 포트
      nodePort: 30080  # 외부에서 접근할 포트 (30000~32767 사이)

