apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  clusterIP: None  # Headless Service 설정
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
