apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # PVC와 동일한 StorageClass 추가
  hostPath:
    path: "/Users/kmj/developer/kubernetes/share"

